runtime: php
env: flex

runtime_config:
    operating_system: "ubuntu22"
    document_root: public

handlers:
- url: /(.*\.(gif|png|jpg|css|js))$
  static_files: public/\1
  upload: public/.*\.(gif|png|jpg|css|js)$
- url: /css/app.css
  static_files: public/\1
  upload: public/css/app.css
- url: /js/app.js
  static_files: public/\1
  upload: public/js/app.js
