options:
  logging: CLOUD_LOGGING_ONLY
  pool: {}
projectId: taskmanager-415712
steps:
- name: gcr.io/k8s-skaffold/pack
  entrypoint: pack
  args:
  - build
  - https://github.com/Univercee/quickdeal.git
  - --builder
  - gcr.io/buildpacks/builder:latest
  - --network
  - cloudbuild